hexaString = "545A003624240406020000000641884907900001120C0D021D1100000008AAC00000019F04D0000E00010B62180983000E3300D42D2D005129D30D0A";

startSymbol = String.fromCharCode(parseInt(hexaString.substring(0, 2), 16)) + String.fromCharCode(parseInt(hexaString.substring(2, 4), 16));
parseInt(hexaString.substring(0, 4), 16);
packetLength = parseInt(hexaString.substring(4, 8), 16);
protocolType = String.fromCharCode(parseInt(hexaString.substring(8, 10), 16)) + String.fromCharCode(parseInt(hexaString.substring(10, 12), 16));

hexaString.substring(8, 12);
hardwareType = hexaString.substring(12, 16);
firmwareVersion = hexaString.substring(16, 24);
imei = hexaString.substring(24, 40);
rtcTime = hexaString.substring(40, 52);
reserved1 = hexaString.substring(52, 56);
stateDataLength = hexaString.substring(56, 60);
alarmType = hexaString.substring(60, 62);
terminalInformation = hexaString.substring(62, 64);
reserved2 = hexaString.substring(64, 68);
batteryVoltage = hexaString.substring(68, 72);
powerVoltage = hexaString.substring(72, 76);
tagInformationDataLength = hexaString.substring(76, 80);
tagType = hexaString.substring(80, 82);
tagNumber = hexaString.substring(82, 84);
tagLength = hexaString.substring(84, 86);
tagId = hexaString.substring(86, 94);
tagStatus = hexaString.substring(94, 96);
tagBatteryVoltage = hexaString.substring(96, 100);
tagTemperature = hexaString.substring(100, 104);
tagHumidity = hexaString.substring(104, 106);
tagRssi = hexaString.substring(106, 108);
packetIndex = hexaString.substring(108, 112);
checkCode = hexaString.substring(112, 116);
stopSymbol = hexaString.substring(116, 120);

console.log(`startSymbol: ${startSymbol}`);
console.log(`packetLength: ${packetLength}`);
console.log(`protocolType: ${protocolType}`);
console.log(`hardwareType: ${hardwareType}`);
console.log(`firmwareVersion: ${firmwareVersion}`);
console.log(`imei: ${imei}`);
console.log(`rtcTime: ${rtcTime}`);
console.log(`reserved1: ${reserved1}`);
console.log(`stateDataLength: ${stateDataLength}`);
console.log(`alarmType: ${alarmType}`);
console.log(`terminalInformation: ${terminalInformation}`);
console.log(`reserved2: ${reserved2}`);
console.log(`batteryVoltage: ${batteryVoltage}`);
console.log(`powerVoltage: ${powerVoltage}`);
console.log(`tagInformationDataLength: ${tagInformationDataLength}`);
console.log(`tagType: ${tagType}`);
console.log(`tagNumber: ${tagNumber}`);
console.log(`tagLength: ${tagLength}`);
console.log(`tagId: ${tagId}`);
console.log(`tagStatus: ${tagStatus}`);
console.log(`tagBatteryVoltage: ${tagBatteryVoltage}`);
console.log(`tagTemperature: ${tagTemperature}`);
console.log(`tagHumidity: ${tagHumidity}`);
console.log(`tagRssi: ${tagRssi}`);
console.log(`packetIndex: ${packetIndex}`);
console.log(`checkCode: ${checkCode}`);
console.log(`stopSymbol: ${stopSymbol}`);
